### ISSUE TITLE
Source files in NPM package

### ISSUE THREAD

**Issue by malekpour** [OfficeDev/office-ui-fabric-react#1365]
### Bug Report

- __Package version(s)__: >2.7.1

#### Describe the issue:

After version 2.7.1 npm package lib folder contains `.ts` files in addition to `.d.ts` files. This causes ts-loader and webpack prefer to compile the typescript source file instead of using compiled `.js` file. My webpack config file contains this section which is very usual in webpack and typescript setups:
```
resolve: {
  extensions: [".js", ".tsx", ".ts"]
}
```
I think source files should be excluded from the npm package or at least comes in a separate folder like `src`.

Not sure, but I think typescript language server behaves the same (recompile instead of just using `.d.ts` files) as ts-loader and this may cause issues.

**Comment by dzearing** [comment]
@malekpour thanks for the issue. I'm not quite understanding though 100%.

The only ts/tsx files we binplace into lib are the Example.tsx files and the Props.ts files. We needed to do this because that way the website could bundle both the js code, but also use raw-loader to load the source code.

Are they causing a build error?

**Comment by malekpour** [comment]
I only imported Button like:
```ts
import { Button } from 'office-ui-fabric-react/lib/Button';
```
and after upgrading to 2.9.0 I an getting this error:
```
ERROR in node_modules\office-ui-fabric-react\lib\components\Button\Button.Props.ts
(11,3): error TS7010: 'focus', which lacks return-type annotation, implicitly has an 'any' return type.
webpack: Failed to compile.
```

**Comment by cschleiden** [comment]
You are using the `no-implicit-any` compiler setting? 

Maybe we should be more explicit and add `: void` to the `focus();` method in the `IButton` interface

**Comment by malekpour** [comment]
I am not using `noImplicitThis` and the following is my typescript generated `tsconfig.json`. I added `: void` to the `focus()` method and it compiled successfully. Still I don't understand what is the benefit of using `.Props.ts` instead of `.Props.d.ts`.
```json5
{
  "compilerOptions": {
    /* Basic Options */                       
    "target": "es5",                          /* Specify ECMAScript target version: 'ES3' (default), 'ES5', 'ES2015', 'ES2016', 'ES2017', or 'ESNEXT'. */
    "module": "commonjs",                     /* Specify module code generation: 'commonjs', 'amd', 'system', 'umd' or 'es2015'. */
    "lib": [
      "dom",
      "es5",
      "es2015.iterable",
      "es2015.promise"
    ],                                        /* Specify library files to be included in the compilation:  */
    // "allowJs": true,                       /* Allow javascript files to be compiled. */
    "jsx": "react",                           /* Specify JSX code generation: 'preserve', 'react-native', or 'react'. */
    // "declaration": true,                   /* Generates corresponding '.d.ts' file. */
    "sourceMap": true,                        /* Generates corresponding '.map' file. */
    // "outFile": "./",                       /* Concatenate and emit output to single file. */
    // "outDir": "./",                        /* Redirect output structure to the directory. */
    // "rootDir": "./",                       /* Specify the root directory of input files. Use to control the output directory structure with --outDir. */
    // "removeComments": true,                /* Do not emit comments to output. */
    // "noEmit": true,                        /* Do not emit outputs. */
    "importHelpers": true,                    /* Import emit helpers from 'tslib'. */
    // "downlevelIteration": true,            /* Provide full support for iterables in 'for-of', spread, and destructuring when targeting 'ES5' or 'ES3'. */
    // "isolatedModules": true,               /* Transpile each file as a separate module (similar to 'ts.transpileModule'). */
                                              
    /* Strict Type-Checking Options */        
    "strict": true                            /* Enable all strict type-checking options. */
    // "noImplicitAny": true,                 /* Raise error on expressions and declarations with an implied 'any' type. */
    // "strictNullChecks": true,              /* Enable strict null checks. */
    // "noImplicitThis": true,                /* Raise error on 'this' expressions with an implied 'any' type. */
    // "alwaysStrict": true,                  /* Parse in strict mode and emit "use strict" for each source file. */
                                              
    /* Additional Checks */                   
    // "noUnusedLocals": true,                /* Report errors on unused locals. */
    // "noUnusedParameters": true,            /* Report errors on unused parameters. */
    // "noImplicitReturns": true,             /* Report error when not all code paths in function return a value. */
    // "noFallthroughCasesInSwitch": true,    /* Report errors for fallthrough cases in switch statement. */
    ...
  }
}
```

**Comment by dzearing** [comment]
@malekpour There isn't a "benefit", but rather, it lets an external package (specifically the public website project) to consume the original file for auto documentation.

If we had a better flow for auto documentation which say converted the Props.tsx to json blobs, that worked in a webpack only scenario, then dropping the Props.tsx files wouldn't be an issue.

We can fix the errors by updating the types. Are there any other errors you hit?

**Comment by dzearing** [comment]
I've patched that specific method.

**Comment by dzearing** [comment]
@malekpour that interface should be fixed in 2.10.0. We still have the ts files in lib. If it still causes issues let me know.

**Comment by malekpour** [comment]
@dzearing I tried 2.10.1 and worked for me. Thanks you!
