### ISSUE TITLE
Couldn't render component in asp.net core react/redux project.

### ISSUE THREAD

**Issue by zhr1130** [OfficeDev/office-ui-fabric-react#6685]
I created a aps.net core with react/redux project in VS2017. And nothing works for me, I tried Nav and PrimaryButton. It threw error: __WEBPACK_IMPORTED_MODULE_1_react__.createContext is not a function.

Repro step:
In VS2017, create a aps.net core project and select react & redux on the second page. 
Insatll office-ui-fabric-react package.
Try render Nav or PrimaryButton. 

Package versions:
.net core : 2.1
react: 16.2.0
office-ui-fabric-react: 6.84.0

Browser: Edge, Chrome. 
OS version: windows 10
 
#### Priorities and help requested:
 
Are you willing to submit a PR to fix? (No)
 
Requested priority: (High)

**Comment by KevinTCoughlin** [comment]
Hey @zhr1130 I don't believe that `react.createContext` is available in `16.2.0`. Can you try using `react@16.3.0` and see if that fixes your issue?

**References**

Grep for `createContext` in the following:

- https://cdnjs.cloudflare.com/ajax/libs/react/16.2.0/cjs/react.development.js
- https://cdnjs.cloudflare.com/ajax/libs/react/16.3.0/cjs/react.development.js

**Comment by zhr1130** [comment]
Hey @KevinTCoughlin ,

After upgrading to react@16.3.2, I got different error. I just tried to render <PrimaryButton> in index.tsx.
Element type is invalid: expected a string (for built-in components) or a class/function (for composite components) but got: object.

Check the render method of `CustomizedPrimaryButton`.

**Comment by dzearing** [comment]
@zhr1130 this isn't enough information; if we don't have a repro or line numbers, we can't figure much out. Can you please debug in and find exactly what line of code is causing you problems? Or recreate the issue in a codepen?

**Comment by zhr1130** [comment]
@dzearing , after upgrading react/react-dom to 16.5, it's fixed. Should .net core team update their template  to use latest react ? Please close this issue. Thanks.
