### ISSUE TITLE
How to use office-ui-fabric-react Dialog

### ISSUE THREAD

**Issue by russgove** [OfficeDev/office-ui-fabric-react#3258]
Hi, 
I copy and pasted the sample code into my own spfx webpart:
   ```
 <Dialog
        isOpen={ !this.state.hideNewRequestDialog }
          onDismiss={ this._closeDialog }
          dialogContentProps={ {
            type: DialogType.normal,
            title: "All emails together",
            subText: "Your Inbox has changed. No longer does it include favorites, it is a singular destination for your emails."
          } }
          modalProps={ {
            isBlocking: true,
            containerClassName: "ms-dialogMainOverride"
          } }
        >
```

I get an error saying  Property 'dialogContentProps' does not exist on type 'IntrinsicAttributes & IntrinsicClassAttributes<Dialog> & IDialogProps & { children?: ReactNode; }'.

What am I doing wrong? are there other samples of this somewhere?

**Comment by russgove** [comment]
anybody got any ideas on this?

**Comment by erichdev** [comment]
@russgove What version of Fabric are you using? I was able to recreate the docs site example without error

**Comment by russgove** [comment]
i'm using 2.34.21. that's the version that comes with spgx

**Comment by LeopoldLerch** [comment]
Which version of Typescript are you running. There was a need to adapt fabric to work with the current version of TS some time ago. If you are on Typescript 2.4 or higer i would recommend you to try if it works with Typescript 2.2. (and then you can try to move onwards slightly).

As you are bound to specific versions of modules in spfx, you have also to be stick on the typescript version that your modules support.

**Comment by manishgarg1** [comment]
Hi @russgove. did this issue get fixed for you? The error makes me feel you are using a react prop that is not a prop on the Dialog React component. This could be because the documentation you read is from the Fabric site and is for a different version of Fabric React than included in your package.

**Comment by russgove** [comment]
thanks for following through. i lost track of the issue so closing
