### ISSUE TITLE
Package fails to build with Node 8.0.0

### ISSUE THREAD

**Issue by carruthe** [OfficeDev/office-ui-fabric-react#1917]
### Bug Report

- __Package version(s)__: 4.3.0
- __Browser and OS versions__: OS X

#### Priorities and help requested (not applicable if asking question):

Are you willing to submit a PR to fix? (Yes, No) No

Requested priority: (Blocking, High, Normal, Low) High 

Products/sites affected: (if applicable)

#### Describe the issue:

When trying to build the repo with Node 8.0.0, I get the following error:

> Error: Your dev environment is running Node.js version v8.0.0 which does not meet the requirements for building this repository.  (The rush.json configuration requires nodeSupportedVersionRange=">=6.9.0 <8.0.0")

I changed the line in rush.json to 

`nodeSupportedVersionRange=">=6.9.0 <9.0.0"`

and it built fine.

Nick

Thanks!

**Comment by dzearing** [comment]
I tried updating to 8 last week and ran into build breaks, something may have been patched since. i will try again later.

**Comment by dzearing** [comment]
https://travis-ci.org/OfficeDev/office-ui-fabric-react/builds/239790350?utm_source=github_status&utm_medium=notification

What a mess. @carruthe Care to take a look into whats up here? I see a lot of fail in the npm install...

```bash
error: ‘Maybe’ does not name a type

./../nan/nan_converters_43_inl.h:22:1: error: ‘return_t’ in ‘struct Nan::imp::ToFactory<v8::Boolean>’ does not name a type

etc
.```

Then after a ton of fail, rush will try to link things and finds packages missing.

```
error: The dependency "deasync" needed by "@microsoft/gulp-core-build-serve" was not found the common folder -- do you need to run "rush generate"?
```

**Comment by carruthe** [comment]
Strange -
The rush.json statement is missing an "=" in the "<=8.0.0" statement.  When I fix that, it builds and runs fine on OS X 10.12.5.  When I try to do the same on Windows 10, I get that mess of errors.  I'll try to see what I can figure out.

**Comment by carruthe** [comment]
I don't know if this has anything to do with it, but both in the Linux build you referenced and my Windows Build, it points to a non-existant version of sass/node-sass (3.13.1)

`Found PhantomJS at /usr/local/phantomjs/bin/phantomjs ...verifying
PhantomJS detected, but wrong version 1.9.8 @ /usr/local/phantomjs/bin/phantomjs.
Downloading https://github.com/Medium/phantomjs/releases/download/v2.1.1/phantomjs-2.1.1-linux-x86_64.tar.bz2
Saving to /home/travis/build/OfficeDev/office-ui-fabric-react/common/temp/npm-tmp/phantomjs/phantomjs-2.1.1-linux-x86_64.tar.bz2
Receiving...
 https://github.com/sass/node-sass/releases/download/v3.13.1/linux-x64-57_binding.node
Cannot download "https://github.com/sass/node-sass/releases/download/v3.13.1/linux-x64-57_binding.node": `

**Comment by carruthe** [comment]
I get the same sass error on my OS X build, so unlikely to be the culprit - I'll keep looking.

**Comment by dzearing** [comment]
Huh. I updated to npm 5.0.3 dependency and the build passes. I'm still seeing confusing errors from the sass install though.
