### ISSUE TITLE
Cannot find module 'office-ui-fabric-react/lib/Text'

### ISSUE THREAD

**Issue by harrychen1** [OfficeDev/office-ui-fabric-react#9392]
Try to use "Text" component after installed "office-ui-fabric-react": "6.143.0".

import * as React from "react";
import { Text } from 'office-ui-fabric-react/lib/Text';

However, this gives the following error.

**_Cannot find module 'office-ui-fabric-react/lib/Text'_**

Has this component been removed? I've been using many other components without any issue.

Thanks.

**Comment by natalieethell** [comment]
Hey @harrychen1 thanks for opening this issue! It looks like Text wasn't added to the office-ui-fabric-react package until version 6.144.0 (https://github.com/OfficeDev/office-ui-fabric-react/pull/8070#issuecomment-467439313). Have you tried that version?

**Comment by harrychen1** [comment]
Thanks for the quick response! I'll give a try.

**Comment by harrychen1** [comment]
This is interesting. 

This is included in version "6.144.0". However, not ion latest version that is "6.189.3".

Not sure why this is not in the latest version but will use version "6.144.0" at this time.

Thanks!

**Comment by natalieethell** [comment]
@harrychen1 oh strange, I'm seeing it work fine in this CodePen. https://codepen.io/naethell/pen/WqeVbm Is it just Text that isn't working for you in that version, or is it other controls, too?

**Comment by harrychen1** [comment]
Yes, it's working for  "6.144.0" version. I'll use this version at this time.

Thanks for the quick response.

**Comment by natalieethell** [comment]
Great! I should have been more clear, but I meant to say that it should work in version 6.189.3, too. My CodePen above is using 6.189.3.
