### ISSUE TITLE
CompoundButton no longer accepts onClick prop when updated from office-ui-fabric-react 4.20.0 to 4.33.0

### ISSUE THREAD

**Issue by kngrace** [OfficeDev/office-ui-fabric-react#2511]
### Bug Report

- __Package version(s)__: 4.20.0 and 4.33.0
- __Browser and OS versions__: n/a  (Chrome/Win10)

#### Priorities and help requested (not applicable if asking question):

Are you willing to submit a PR to fix? No

Requested priority: Normal (Blocking adoption of v4.33.0 but can downgrade back to v4.20.0)

Products/sites affected: n/a

#### Describe the issue:

When I updated from office-ui-fabric-react 4.20.0 to 4.33.0, I receive an error in my compiler that states: 

> Error:(61, 11) TS2339:Property 'onClick' does not exist on type 'IntrinsicAttributes & IntrinsicClassAttributes<CompoundButton> & IButtonProps & { children?: Reac...'.

#### Actual behavior:

Either unable to compile due to error or unable to pass onClick prop to this CompoundButton object.

#### Expected behavior:

I should be able to pass an onClick prop to any Button object. 

Example of expected behavior: The PrimaryButton code includes an onClick prop in the source. URL: https://dev.office.com/fabric#/components/button

### If applicable, please provide a codepen repro:

n/a

**Comment by nvgopi** [comment]
Also, Is it possible to downgrade to a version where it is working? I am a newbie. Any directions would be helpful.

**Comment by cjsheets** [comment]
This looks related to the @types/react upgrade to 15.0.38 made in v4.29.0

It's mentioned in the [release notes](https://github.com/OfficeDev/office-ui-fabric-react/releases/tag/office-ui-fabric-react_v4.29.0) The solution is upgrading reacts typings.

**Comment by kngrace** [comment]
This appears to be related to those breaking changes in react (which are surfaced by the @types/react upgrade). So essentially I need to ensure I'm running compatible version of office-ui-fabric-react and react. 

Once SPFx's Yeoman generator is updated to include the newer version of react, I'll look into upgrading office-ui-fabric-react as well. I noticed some discussion around it but one of the comments essentially said that all of the code samples will have to be redone to adjust to react changes.
