### ISSUE TITLE
another spfx with latest office-ui-fabric-react issue

### ISSUE THREAD

**Issue by peterremote1980** [OfficeDev/office-ui-fabric-react#5181]
If i delete <DefaultButton text="Button" />, everything back to work.

```
{
	"name": "coding-news",
	"version": "0.0.1",
	"private": true,
	"engines": {
		"node": ">=0.10.0"
	},
	"scripts": {
		"build": "gulp bundle",
		"clean": "gulp clean",
		"test": "gulp test"
	},
	"dependencies": {
		"@microsoft/sp-core-library": "~1.4.1",
		"@microsoft/sp-lodash-subset": "~1.4.1",
		"@microsoft/sp-office-ui-fabric-core": "~1.4.1",
		"@microsoft/sp-webpart-base": "~1.4.1",
		"@types/react": "16.3.17",
		"@types/react-dom": "16.0.6",
		"@types/webpack-env": ">=1.12.1 <1.14.0",
		"chart.js": "2.7.2",
		"jquery": "^3.3.1",
		"office-ui-fabric-react": "^6.9.0",
		"react": "16.4.0",
		"react-dom": "16.4.0",
		"react-chartjs": "^1.2.0"
	},
	"devDependencies": {
		"@microsoft/sp-build-web": "~1.4.1",
		"@microsoft/sp-module-interfaces": "~1.4.1",
		"@microsoft/sp-webpart-workbench": "~1.4.1",
		"gulp": "~3.9.1",
		"@types/chai": "4.1.3",
		"@types/mocha": "5.2.2",
		"ajv": "6.5.1"
	}
}
```

```
import * as React from 'react';
import styles from './CodingNews.module.scss';
import { ICodingNewsProps } from './ICodingNewsProps';
import { escape } from '@microsoft/sp-lodash-subset';
import { DefaultButton, IButtonProps } from 'office-ui-fabric-react/lib/Button';
import { Label } from 'office-ui-fabric-react/lib/Label';

export default class CodingNews extends React.Component<ICodingNewsProps, {}> {
	public render(): React.ReactElement<ICodingNewsProps> {
		return (
			<div className={styles.codingNews}>
				<div className={styles.container}>
					<div className={styles.row}>
						<div className={styles.column}>
							<span className={styles.title}>Welcome to SharePoint!</span>
							<p className={styles.subTitle}>Customize SharePoint experiences using Web Parts.</p>
							<p className={styles.description}>{escape(this.props.description)}</p>
							<a href="https://aka.ms/spfx" className={styles.button}>
								<span className={styles.label}>Learn more</span>
							</a>

							<DefaultButton
								text="Button"
							/>
						</div>
					</div>
				</div>
			</div>
		);
	}
}
```

Error:
```
[SPLoaderError.loadComponentError]:
***Failed to load component "aff94c45-b9d9-4d82-b0ed-1756e97de86a" (CodingNewsWebPart).
Original error: ***Failed to load entry point from component "aff94c45-b9d9-4d82-b0ed-1756e97de86a" (CodingNewsWebPart).
Original error: Error loading https://component-id.invalid/aff94c45-b9d9-4d82-b0ed-1756e97de86a_0.0.1
	__WEBPACK_IMPORTED_MODULE_0__uifabric_merge_styles__["a" /* Stylesheet */].getInstance().onReset is not a function. (In '__WEBPACK_IMPORTED_MODULE_0__uifabric_merge_styles__["a" /* Stylesheet */].getInstance().onReset(resetIds)', '__WEBPACK_IMPORTED_MODULE_0__uifabric_merge_styles__["a" /* Stylesheet */].getInstance().onReset' is undefined)

***INNERERROR:
***Failed to load entry point from component "aff94c45-b9d9-4d82-b0ed-1756e97de86a" (CodingNewsWebPart).
Original error: Error loading https://component-id.invalid/aff94c45-b9d9-4d82-b0ed-1756e97de86a_0.0.1
	__WEBPACK_IMPORTED_MODULE_0__uifabric_merge_styles__["a" /* Stylesheet */].getInstance().onReset is not a function. (In '__WEBPACK_IMPORTED_MODULE_0__uifabric_merge_styles__["a" /* Stylesheet */].getInstance().onReset(resetIds)', '__WEBPACK_IMPORTED_MODULE_0__uifabric_merge_styles__["a" /* Stylesheet */].getInstance().onReset' is undefined)
***CALLSTACK:
SPError@https://localhost:4321/node_modules/@microsoft/sp-loader/dist/sp-loader-assembly_en-us.js:10183:33
SPLoaderError@https://localhost:4321/node_modules/@microsoft/sp-loader/dist/sp-loader-assembly_en-us.js:4211:32
SPLoaderError@[native code]
buildErrorWithVerboseLog@https://localhost:4321/node_modules/@microsoft/sp-loader/dist/sp-loader-assembly_en-us.js:3821:146
https://localhost:4321/node_modules/@microsoft/sp-loader/dist/sp-loader-assembly_en-us.js:7952:61
promiseReactionJob@[native code]
```

**Comment by lling1105** [comment]
i encountered the same issue :(

**Comment by cliffkoh** [comment]
@SriDeshpande can you take a look at this?

**Comment by gosiaborzecka** [comment]
I have the same issue - OfficeUIFabricReact not working with SPFx 1.5.0 :(

**Comment by countvm** [comment]
Same issue with spfx 1.5.0

**Comment by peterremote1980** [comment]
spfx is not well tested version

**Comment by SvenLauterbach** [comment]
I don't know if this is a Office UI Frabric React, SPFX or Office Online problem.

The problem is  Office 365 loads an "spofiles_mini.js" file, which includes an old version of the [mergeStyle](https://github.com/OfficeDev/office-ui-fabric-react/tree/master/packages/merge-styles) module. 

In this module there is a function "getInstance()" in the [Stylesheet.ts](https://github.com/OfficeDev/office-ui-fabric-react/blob/master/packages/merge-styles/src/Stylesheet.ts), this function is a Singleton, which checks if the window objects contains a Stylesheet instance and if not creates one.

The problem is, that spofiles_mini.js is loaded before the SPFX Webpart/Extension and it puts an "old" Stylesheet object into the global window. When the SPFX webpart is loaded, the Stylesheet instance loads the old object from the window (because its a Singleton).

The old Stylesheet object is missing the "onReset" function, hence the error. You can compare the spofiles-mini.js Stylesheet object (line 4005 or search for = "__stylesheet__") with the current Stylesheet.ts version to see the difference and the missing function.

**Comment by dmitrydyachenko** [comment]
I am experiencing the issue with "office-ui-fabric-react": "^6.9.0".

**Comment by cliffkoh** [comment]
Hi all, @srideshpande has investigated and is exploring a long-term solution for the issue encountered. His recommendation for the time being is to use the same version of office-ui-fabric-react that SPFX is using, which is 5.112.0 as a workaround (alternatively, anything before 6.8.0 might work as well).

**Comment by cliffkoh** [comment]
This is fixed in #5253.

**Comment by dzearing** [comment]
Will be published tonight, sorry for the friction.

**Comment by dzearing** [comment]
The fix is now published in 6.16.0 and dependencies. Again apologies for the nullref, we've addressed the check and we're looking at a more comprehensive solution to avoid it in the future.

**Comment by jenkinsns** [comment]
After upgrade from 5.131.0 to 6.16.0 it throws below error

[01:56:17] Error - [tsc] node_modules/@uifabric/merge-styles/lib/IStyleSet.d.ts(15,67): error TS1005: ';' expected.
[01:56:17] Error - [tsc] node_modules/@uifabric/merge-styles/lib/IStyleSet.d.ts(15,114): error TS1005: '(' expected.
[01:56:17] Error - [tsc] node_modules/@uifabric/merge-styles/lib/IStyleSet.d.ts(15,136): error TS1005: '(' expected.
[01:56:17] Error - 'tsc' sub task errored after 14 s
 exited with code 2

**Comment by cliffkoh** [comment]
Fabric 6 has a requirement on TypeScript 2.8. Is there a SPFx release that supports TypeScript 2.8 yet? 

You can otherwise try to pin `@uifabric/merge-styles` to the minbar specified in the 6.16.0 package.json, which is `6.2.0` per https://unpkg.com/office-ui-fabric-react@6.16.0/package.json, and that should unblock you.
